config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="#">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Feedback</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Advertise</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="page-contact.html">Contact</a>
      </li>
    </ul>
    <div class="copy">
      <%= copyright_generator %>
    </div>
  </div>

app/views/shared/_blog_footer.html.erb
<footer class="site-footer" role="contentinfo">
  <div class="container">

    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="#">Back to top</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Terms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Feedback</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Advertise</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="page-contact.html">Contact</a>
      </li>
    </ul>
    <div class="copy">
      <%= copyright_generator %>
    </div>
  </div>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Thanks for visiting me!</p>
    <span>
      <%= link_to 'Write a New Blog Post', new_blog_path if logged_in?(:site_admin)%>
    </span> /
    <span>
      <%= link_to 'Topics', topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="sidebar sidebar-sticky">
  <div class="card mb-4">
    <h4>About</h4>
    <p>Welcome! Thanks for visiting my website, feel free to check out my blog as well, comment, ask questions or reach out.</p>

    <%= source_helper("alert alert-info blog-sidebar-source") %>
  </div>
  <div class="card mb-4">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>
    <div class="card mb-4">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/Jdcorley" target="_blank" <%= fa_icon "github" %></a></li>
      <li><a href="https://www.linkedin.com/in/jack-corley-00242211a" target="_blank" <%= fa_icon "linkedin" %></a></li>
      <li><a href="https://medium.com/@jdcorley" target="_blank" <%= fa_icon "medium" %></a></li>
      <li><a href="https://twitter.com/JackCorley12" target="_blank" <%= fa_icon "twitter" %></a></li>
    </ol>
    </div>
</aside>

app/views/shared/_nav.html.erb
<header role="banner">
  <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
    <div class="container">
      <button class="navbar-toggler order-2 order-md-1" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse order-3 order-md-2" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home</a>
            <div class="dropdown-menu" aria-labelledby="dropdown02">
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to "About", about_me_path, class: "dropdown-item" %>
              <%= link_to "Contact", contact_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Blog</a>
            <div class="dropdown-menu" aria-labelledby="dropdown02">
              <%= link_to "Blog", blogs_path, class: "dropdown-item"  %>
              <%= link_to_if(logged_in?(:site_admin),'Write a New Blog Post', new_blog_path, class: "dropdown-item") do end %>
              <%= link_to 'Topics', topics_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Portfolio</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              <%= link_to "Portfolio", portfolios_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
      <%= link_to "Jack Corley", root_path, class: "navbar-brand mx-auto order-1 order-md-3" %>
      <div class="collapse navbar-collapse order-4 order-md-4" id="navbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= login_helper 'nav-link', 'a' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View All Portfolio Items', portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <p></p>
    <p>
     <%= copyright_generator  %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<ul>
  <%= nav_helper '', 'li' %>
  <%= login_helper 'li' %>
</ul>